### ISSUE TITLE
Usage on Espruino

### ISSUE THREAD

**Issue by wilberforce** [pirumpi/tiny-router#8]
Hi. How do you install to use on Espruino?

I get "module path not found".

I have set up a project and added tiny-router.js to /project/modules, as I could not get the npm load to work.

**Comment by Coder2012** [comment]
Is this project still being maintained?

I would also like to know how to use this library on the Espruino. Works very well on the Tessel2.

**Comment by pirumpi** [comment]
I'm working on some examples for the espruino, but it is taking me longer
than expected.

**Comment by Coder2012** [comment]
No problem, thanks for the update.
